### ISSUE TITLE
Rename kibana3 to puppet-kibana3

### ISSUE THREAD

**Issue by Spredzy** [thejandroman/puppet-kibana3#11]
Hi @thejandroman, would you mind renaming the repo puppet-kibana3 instead of kibana3 since it is a puppet module ?

It makes it easier, for module management and fork management, to assume that every module are appended with 'puppet-'.

Thanks in advance,

--
Spredzy

**Comment by thejandroman** [comment]
Done.

**Comment by Spredzy** [comment]
@thejandroman thanks !
